import streamlit as st
import pandas as pd
import numpy as np
import os
import xgboost as xgb
import joblib
import torch
import torch.nn as nn

# --- Define Paths ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODELS_DIR = os.path.join(BASE_DIR, 'models', 'saved_models')
OUTPUTS_DIR = os.path.join(BASE_DIR, 'outputs')

# --- Define the DQN Brain Structure ---
class QNetwork(nn.Module):
    def __init__(self, state_size, action_size):
        super(QNetwork, self).__init__()
        self.fc1 = nn.Linear(state_size, 64)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(64, 64)
        self.out = nn.Linear(64, action_size)

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        return self.out(x)

# --- Page Setup ---
st.set_page_config(page_title="Railway Digital Twin AI", layout="wide")
st.title("🚆 Live AI Railway Control Center")
st.markdown("Integrating **XGBoost** (Predictive) and **Deep Q-Learning** (Prescriptive) into the new Digital Twin.")

# --- Load Models ---
@st.cache_resource
def load_xgboost():
    try:
        model = xgb.XGBRegressor()
        model.load_model(os.path.join(MODELS_DIR, 'xgboost_delay_model.json'))
        le_train = joblib.load(os.path.join(MODELS_DIR, 'le_train_type.pkl'))
        le_station = joblib.load(os.path.join(MODELS_DIR, 'le_station_code.pkl'))
        return model, le_train, le_station
    except Exception as e:
        return None, None, None

@st.cache_resource
def load_dqn():
    try:
        model = QNetwork(4, 2) # 4 states in, 2 actions out
        model.load_state_dict(torch.load(os.path.join(MODELS_DIR, 'dqn_railway_model.pth')))
        model.eval()
        return model
    except Exception as e:
        return None

xgb_model, le_train, le_station = load_xgboost()
dqn_model = load_dqn()

col1, col2 = st.columns(2)

# ==========================================
# COLUMN 1: LIVE AI DISPATCHER (DQN)
# ==========================================
with col1:
    st.header("🧠 Live Network Optimizer (DQN)")
    st.markdown("Reads live data from the Digital Twin to recommend track actions.")
    
    result_csv = os.path.join(OUTPUTS_DIR, "simulation_results.csv")
    
    if st.button("🔄 Fetch Live Simulation Data"):
        if os.path.exists(result_csv):
            # Read the live simulation data generated by run_digital_twin.py
            df = pd.read_csv(result_csv)
            if not df.empty:
                latest = df.iloc[-1]
                
                sim_time = latest["step"]
                live_trains = latest["active_trains"]
                avg_speed = latest["avg_speed"]
                congestion = latest["congestion_index"]
                
                # Estimate halted trains based on congestion for the AI state
                halted_trains = int(live_trains * (congestion if pd.notnull(congestion) else 0))
                
                st.write(f"**⏱️ Sim Time:** {sim_time}s | **🚆 Active Trains:** {live_trains}")
                st.write(f"**💨 Avg Speed:** {avg_speed:.2f} m/s | **🚦 Congestion:** {congestion:.2f}")
                
                if dqn_model:
                    # Feed the live data directly into the DQN brain!
                    state = np.array([live_trains, avg_speed, halted_trains, sim_time], dtype=np.float32)
                    state_tensor = torch.FloatTensor(state).unsqueeze(0)
                    
                    with torch.no_grad():
                        q_values = dqn_model(state_tensor)
                        action = np.argmax(q_values.numpy())
                        
                    st.markdown("---")
                    if action == 1 or congestion > 0.6:
                        st.error("⚠️ **AI ACTION REQUIRED:** High Congestion detected. Switch Express trains to SLOW line to prevent gridlock.")
                    else:
                        st.success("✅ **AI STATUS:** Normal Operations. Network flow is optimal.")
                else:
                    st.error("DQN Model not found.")
            else:
                st.warning("Simulation data is empty. Run the simulation first!")
        else:
            st.error("No live simulation data found. Is SUMO running?")

# ==========================================
# COLUMN 2: XGBOOST DELAY PREDICTION
# ==========================================
with col2:
    st.header("📈 Predictive Engine (XGBoost)")
    st.markdown("Predict the specific delay of an approaching train.")
    
    if xgb_model and le_train and le_station:
        with st.form("predict_form"):
            hour = st.slider("Hour of Day", 0, 23, 14)
            prev_delay = st.number_input("Delay at Previous Station (minutes)", min_value=0.0, value=2.5)
            
            train_type = st.selectbox("Train Type", le_train.classes_)
            station_code = st.selectbox("Approaching Station", le_station.classes_)
            dispatch_priority = st.selectbox("Dispatch Priority (0=High, 2=Low)", [0, 1, 2]) 
            
            submitted = st.form_submit_button("Predict Future Delay")
            
            if submitted:
                t_encoded = le_train.transform([train_type])[0]
                s_encoded = le_station.transform([station_code])[0]
                features = np.array([[hour, prev_delay, t_encoded, s_encoded, dispatch_priority]])
                
                prediction = xgb_model.predict(features)[0]
                prediction = max(0, prediction) 
                
                st.info(f"🔮 **Predicted Delay at {station_code}:** {prediction:.2f} minutes")